# Generated by Django 5.1.7 on 2025-04-03 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='hotel_slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
