# Generated by Django 5.1.7 on 2025-04-03 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_hotel_hotel_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelvendor',
            name='business_name',
            field=models.CharField(default='Default Business', max_length=100),
        ),
    ]
