# Generated by Django 5.1.7 on 2025-03-21 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hoteluser',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hotelvendor',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
